package com.prodops.controltower.mcp.domain.model;

public enum CoverageGapType {
  TRACE_PROPAGATION_MISSING,
  SERVICE_VERSION_MISSING,
  REPO_MAPPING_MISSING,
  DEPLOYMENT_METADATA_MISSING,
  LOG_FIELDS_INSUFFICIENT,
  TRACE_TAGS_INSUFFICIENT,
  NO_PIPELINE_METADATA,
  NO_DATA_VIEW_HINT,
  EVIDENCE_TIME_GAP
}
